[package]
name = "submission_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.29"
tempfile = "3.6"
wait-timeout = "0.2"
lazy_static = "1.4"
once_cell = "1.18"
